### ISSUE TITLE
Package 'libjson-c4' has no installation candidate

### ISSUE THREAD

**Issue by xhalo32** [mviereck/dockerfile-x11docker-sway#1]
Fails to build:
```bash
Reading package lists...
Building dependency tree...
Reading state information...
Package libjson-c4 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libjson-c4' has no installation candidate
The command '/bin/sh -c ... && apt-get install -y -t experimental libjson-c4 libjson-c-dev scdoc && ...' returned a non-zero code: 100
```

x86_64 GNU/Linux

**Comment by mviereck** [comment]
Thank you for the bug report!

I once found this bug, too. It can likely be fixed with some source repository adjustments in the Dockerfile.
However, I decided not to fix it. From README.md:
> This repository is not maintained anymore. Build error (4/2020): The source for libjson-c4 must be fixed

I've already deleted the image from docker hub, maybe I'll delete this github repo, too.
